### ISSUE TITLE
"AnsibleUndefinedVariable: 'dict object' has no attribute u'server1.example.com'

### ISSUE THREAD

**Issue by mdyasin23** [cloudera/cloudera-playbook#35] opened 2019-06-12 10:49 UTC
Hi,

Im also facing the same issue. Getting error on scm template task. I have modified the inventory file with FQDN also and I have done all possible things but couldn't figure out what is the issue. Appreciated if anyone can provide us quick solution.

TASK [scm : Prepare CMS template] ****************************************************************************
task path: /root/cloudera-playbook/roles/scm/tasks/cms.yml:9

fatal: [server1.example.com]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute u'server1.example.com'"}

==========================================================
Hosts:

[scm_server]
server1.example.com      license_file=/path/to/cloudera_license.txt

[db_server]
server1.example.com

[utility_servers:children]
scm_server
db_server

[gateway_servers]
servergw.example.com        host_template=HostTemplate-Gateway role_ref_names=HDFS-HTTPFS-1

[master_servers]
server1.example.com        host_template=HostTemplate-Master1

[worker_servers]
server2.example.com

[worker_servers:vars]
host_template=HostTemplate-Workers

[cdh_servers:children]
utility_servers
gateway_servers
master_servers
worker_servers

[all:vars]
ansible_user=root

**Comment by lhoss** [comment] 2019-06-26 12:24
I also had such issues with the role, but after many fixes and improvments, I got it working to deploy a cluster on AWS ..
More infos, in the related issue: https://github.com/cloudera/cloudera-playbook/issues/34

**Comment by dbeech** [comment] 2019-09-02 08:56
Hello. This issue would occur if the hostnames in inventory file are different to the hostnames reported by each node's Cloudera Manager agent. Using short names instead of FQDNs is one possibility, and DNS configuration (or misconfiguration) is another. 

Closing as duplicate of #22.

**Closed as completed by dbeech** 2019-09-02 08:56 UTC
